# _config.yml

# Site Settings
title: "Dr. Daniel Hayden"
email: "dhayden1@luc.edu"
description: "My personal website to talk about myself and my research"
baseurl: ""
url: ""

# Build Settings
theme: jekyll-theme-time-machine

# Plugins (optional, but keep it simple)
plugins:
  - jekyll-feed